### ISSUE TITLE
section "walleyeBass" figure content

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#25]
This is where users discover that bass and walleye prefer different habitats, and that you are more likely to find them in certain lakes. 

MVP:
simple mouseover for 
![image](https://cloud.githubusercontent.com/assets/2349007/16081317/92e16eee-32d2-11e6-980b-5caedcb5bf21.png)

nice-to-have:
"you draw it" for trends that let's users try to guess. Reality is revealed after they make an attempt, or scroll past this interaction.
similar to 
![image](https://cloud.githubusercontent.com/assets/2349007/16081365/bb45fe40-32d2-11e6-82f4-fb9d68d34b06.png)

**Comment by jordansread** [comment]
@lindsaycarr I would like feedback on the current user experience: 
https://github.com/USGS-VIZLAB/climate-fish-habitat/blob/master/sandbox/draw_lines.svg

(you'll need to open that file in a browser)

**Comment by jordansread** [comment]
Assigning to lcarr for review and feedback. See discussion in #7

**Comment by lindsayplatt** [comment]
I think I need to fork and open the file into a browser from my computer - doesn't seem to be doing anything when I right click and say "open image in new tab".

**Comment by jordansread** [comment]
yes, you'll either need to download it or fork and open.

**Comment by lindsayplatt** [comment]
@jread-usgs this is all I see when I open the file. I am only seeing the last line segments

![image](https://cloud.githubusercontent.com/assets/13220910/16082867/a15273fa-32d8-11e6-8d6d-f43030e06484.png)

**Comment by lindsayplatt** [comment]
Thoughts on fig:
- before being told it was a "draw your own" scenario, I thought it was broken. There will obviously be more context around this in the actual viz, but I also think that the figure should be able to stand alone. Maybe there should be grey text in the middle of the plot that says "Try drawing the health probability lines for each species" and it goes away once you start drawing. That way if someone completely misses the text above this, they don't think the figure is broken.
- I don't think it is clear that the yellow appears in the sections that are incomplete. The New York Time one blinks - but maybe text can say "keep drawing" instead of it blinking (thinking of things being stand alone again)
- you can click at any height of the graph and it starts drawing Walleye. I would say that there needs to be a larger buffer around LMB hint segments because you currently have to click directly on the first point
- I can change those hint segments by dragging my mouse over them. I think they should be fixed
- I like that you can change points after drawing them already
- Incorporate a "Draw again" button so that people can completely start over (even after revealing the true lines)? Just thinking that people might want to show others the cool fig during the same session
- I know we are probably trying to not do exactly what the NYT fig did, but I really liked how they overlaid your guess with the real line. I might have drawn a couple of the points exactly, but it's hard to tell when you're looking on two different plots

I was testing in Chrome and IE

**Comment by jordansread** [comment]
Thanks! I will chip away at these suggestions and probably ping you to review again in the future.

**Comment by gjahansen2** [comment]
For comparing the one you drew to the actual relationship, why not something like this? Although I would suggest dotted, slightly transparent line for "your guess" and solid line for the true relationships. And the colors can be for the species, as always. 
![image](https://cloud.githubusercontent.com/assets/19436778/16119927/4cecfc74-33a3-11e6-9c50-16b094764ed7.png)

**Comment by gjahansen2** [comment]
I also like how the yellow areas on the NYT viz are accompanied by text at the top saying "keep drawing!" if you don't fill out the whole range.

**Comment by gjahansen2** [comment]
I dislike the characterization of "healthy walleye/bass fishery'. Lots of issues there. How about "Probability of abundant walleye/largemouth bass populations"? Too nerdy?

**Comment by jordansread** [comment]
WAY too nerdy. I figured my choice there wouldn't fly, but it needs to be a compromise with the level of detail we want in the science paper vs for the public. Think along the lines of calling high GDD "warm lakes"

**Comment by gjahansen2** [comment]
We need Jon Hansen to weigh in here. he helps keep my inner nerd at bay.

:couple:

**Comment by gjahansen2** [comment]
It's a pretty big burn to be called WAY too nerdy by you, @jread-usgs :eyeglasses::straight_ruler::iphone::floppy_disk::wink:

**Comment by gjahansen2** [comment]
Probability of abundant bass/walleye. -Jon Hansen

**Comment by jordansread** [comment]
changed ☝️ .

what about just having the user draw one line, walleye, and giving them the line for bass?

![image](https://cloud.githubusercontent.com/assets/2349007/16173401/d6b81510-3565-11e6-8b3e-4e89dbe9e1c7.png)
@gjahansen2

**Comment by gjahansen2** [comment]
that sounds like it could work well!

**Comment by jordansread** [comment]
Ok, I will give that a shot and see how much that helps

**Comment by jordansread** [comment]
see #76
