### ISSUE TITLE
Create storyboard for chapters w/ rough figs and describe potential user experience

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#3]
Straw dog:
1. cool load screen animation
2. Fish are important to economy/tourism and culture [static picture]
3. Fish growth, survival, and reproduction is controlled/influenced by temperature [interactive: select thermal guild for 3~5 fish] -see #4 for prototype
4. Lakes are warming globally, regionally [O'Reilly dataset: map and scatterplot linked?]
5. Lake ice is declining (kind of chapter `4a`) [Magnusson/Sharma dataset: animate lines through time, use hover legend]
6. Projected shifts in fish species dominance [Hansen figure: walk a lake back and forth through the threshold] 
7. Adaptive management can help prioritize action [static stocking pic]
8. Acknowledgements, dataset download

**Comment by jordansread** [comment]
@gjahansen2 if you have edits or ideas, and you comment on this thread?

**Comment by gjahansen2** [comment]
it will have to be next week, but yes. I am on vacation!

On Tue, May 24, 2016 at 3:44 PM, Jordan S Read notifications@github.com
wrote:

> @gjahansen2 https://github.com/gjahansen2 if you have edits or ideas,
> and you comment on this thread?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/USGS-VIZLAB/climate-fish-habitat/issues/3#issuecomment-221384527

## 

Gretchen Hansen
https://gretchenhansen.squarespace.com

**Comment by jordansread** [comment]
@lawinslow

**Comment by lawinslow** [comment]
Some thoughts:
1. We have a fair amount of background info, but don't necessarily talk a lot about our work results (currently only #6 is based on our results I think). We'll have to see how long this gets, but could maybe add some large-scale future viz stuff. Maybe a map or two. Just thinking out loud, maybe aggregate "avg lake temp anomaly" past and future. 
2. "walk back and forth through the threshold" - Its a shame, would be cool if we had continuous future (2000 to 2100) projections so you could see an annual timeseries of GDD that slowly moved its way across the threshold. Right now for future we have discrete 2020-2039 and 2080-2100

**Comment by jordansread** [comment]
yeah, I agree. Anything you want to remove from the background, or are you thinking of adding a chapter for the future?

**Comment by lawinslow** [comment]
I was thinking add, and decide how long it is going to be. If removal is needed, that ice stuff could possibly go. We don't actually do anything with that on this project.

**Comment by gjahansen2** [comment]
I think we should take out the ice out stuff, since it is not really relevant here. I agree with Luke that there might be too much background here and not enough meat. 

One part of the "meat" from the GCB paper that is missing here is the variability among lakes (i.e., some lakes are more resilient than others). This applies both to your #4 (lakes are warming but not all at the same rate or to the same end point - I would emphasize our results more than past studies here) and to your #6 - some lakes will continue to support walleye because either they wont cross the threshold OR they will cross it but they are still predicted to be okay (because they are big, usually).

Since for #6 we don't have continuous predictions (as Luke mentioned), we should brainstorm how best to show changes in fish species dominance in some lakes, but not in others.

**Comment by jordansread** [comment]
current storyboard is here: https://docs.google.com/document/d/1CQRgaEkpJdS7XYXehVNAB-CnbpQ6_SvZRyc5uo9h0lM/edit
