### ISSUE TITLE
Statewide average trends in bass and walleye figure

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#6]
Need data from @gjahansen2 

@jread-usgs will animate

**Comment by jordansread** [comment]
adult abundance vs time please

**Comment by gjahansen2** [comment]
I need some time to figure out some things with the adult data. I provided YOY walleye and bass CPUE for now. For bass, the earlier data is probably sort of unreliable - I would start it at 1990 or 1991.
https://drive.google.com/open?id=0BwCnuHTL_uP9NXZnOTZEVHdUMGM

**Comment by jordansread** [comment]
@gjahansen2 so we should be using `walleye_age0_annual_means` and `fall_lmb8_cpue_annual_mean`?

**Comment by gjahansen2** [comment]
Yes for now. The adult walleye are not sampled as well, and require a more
complicated metric than annual mean. I'll work on it.

**Comment by gjahansen2** [comment]
@jread-usgs I added an adult metric that I think is appropriate, although the units are pretty much meaningless. These are the BLUPs from a mixed model of adult walleye density with random effects for lake and year. I thought I should do this because not many lakes are sampled each year, and lakes vary a lot in their densities, so a simple annual mean doesn't really mean much in this context. This way, I have accounted for differences among lakes, and there is a clear downward trend over time. I would just label the y axis 'relative abundance' if you are going to use this metric (probably for the other data as well, as catch per mile won't mean much to anyone outside of fisheries either.
https://drive.google.com/open?id=0BwCnuHTL_uP9Rl95cVdRUEdLOXc

**Comment by jordansread** [comment]
You want to do the same for LMB, or use those as-is?

**Comment by jordansread** [comment]
what's a BLUP?

**Comment by gjahansen2** [comment]
I think the bass data are ok as is, but I am curious to see what the numbers look like if I do the same thing. Hang tight for a minute. A BLUP is a best linear unbiased predictor - basically the year-specific residuals from a mixed model.

**Comment by gjahansen2** [comment]
http://lmgtfy.com/?q=BLUP

**Comment by jordansread** [comment]
who knows what had come up if I googled that. geez

**Comment by gjahansen2** [comment]
I think the trend is about the same here as using the annual means, but here are the largemouth bass data analyzed in the same way.
https://drive.google.com/open?id=0BwCnuHTL_uP9R0JibUxOU3U5b2M

**Comment by jordansread** [comment]
are we out of luck if we want to start w/ 1991? Should we start w 1994 for both?

**Comment by gjahansen2** [comment]
Yeah, the bass data have some issues pre-1994 (very few lakes in database, and some unreliable data). Would it be weird to start them at different times?

**Comment by jordansread** [comment]
I think that is fine. We can iterate if it seemed weird

**Comment by jordansread** [comment]
see #24
